[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "malcolm-test"
version = "0.12.0"
authors = [
  { name="Seth Grover", email="mero.mero.guero@gmail.com" },
]
description = "A package for performing tests against a Malcolm system"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    'beautifulsoup4==4.14.2',
    'mmguero>=2.0.3',
    'elasticsearch-dsl==8.18.0',
    'elasticsearch==8.18.0',
    'opensearch-py==3.0.0',
    'petname==2.6',
    'psutil==7.1.2',
    'pytest==8.4.2',
    'python-magic==0.4.27',
    'requests==2.32.5',
    'stream-unzip==0.0.99',
    'tomli-w==1.2.0',
    'tomli==2.3.0'
]

[project.urls]
Homepage = "https://github.com/idaholab/malcolm-test"
Issues = "https://github.com/idaholab/malcolm-test/issues"
Artifacts = "https://github.com/idaholab/malcolm-test-artifacts"
PyPI = "https://pypi.org/project/malcolm-test/"

[project.scripts]
malcolm-test = "maltest:main"

[tool.hatch.build.targets.wheel]
packages = ["src/maltest"]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
